pipeline:
  build:
    image: golang:1.8
    commands: 
      - go get github.com/joho/godotenv/cmd/godotenv
      - go get github.com/drone/drone/drone
      - find /

  publish:
    image: plugins/docker
    repo: cyberplant/drone
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push

  notify:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
    when:
      status: [ success, failure ]
