pipeline:
  build:
    image: golang:1.8
    commands: 
      - go get github.com/joho/godotenv/cmd/godotenv
      - go build -v -o release/godotenv github.com/joho/godotenv/cmd/godotenv
      - go get github.com/drone/drone/drone
      - go build -v -o release/drone github.com/drone/drone/drone

  publish:
    image: plugins/docker
    repo: luar/drone
    secrets: [ docker_username, docker_password ]
    # tag: [ latest ]
    #when:
    #  branch: master
    #  event: push

  notify:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
    when:
      status: [ success, failure ]
